In [9]:
import pandas as pd 
import numpy as np
data = r'D:\Country-development-analysis\global-development-analysis\data\Country-data.csv'
df = pd.read_csv(data)
df.head()

               country  child_mort  exports  ...  life_expec  total_fer   gdpp
0          Afghanistan        90.2     10.0  ...        56.2       5.82    553
1              Albania        16.6     28.0  ...        76.3       1.65   4090
2              Algeria        27.3     38.4  ...        76.5       2.89   4460
3               Angola       119.0     62.3  ...        60.1       6.16   3530
4  Antigua and Barbuda        10.3     45.5  ...        76.8       2.13  12200

[5 rows x 10 columns]

In [10]:
df

                 country  child_mort  exports  ...  life_expec  total_fer   gdpp
0            Afghanistan        90.2     10.0  ...        56.2       5.82    553
1                Albania        16.6     28.0  ...        76.3       1.65   4090
2                Algeria        27.3     38.4  ...        76.5       2.89   4460
3                 Angola       119.0     62.3  ...        60.1       6.16   3530
4    Antigua and Barbuda        10.3     45.5  ...        76.8       2.13  12200
..                   ...         ...      ...  ...         ...        ...    ...
162              Vanuatu        29.2     46.6  ...        63.0       3.50   2970
163            Venezuela        17.1     28.5  ...        75.4       2.47  13500
164              Vietnam        23.3     72.0  ...        73.1       1.95   1310
165                Yemen        56.3     30.0  ...        67.5       4.67   1310
166               Zambia        83.1     37.0  ...        52.0       5.40   1460

[167 rows x 10 columns]

In [11]:
df.drop(['country'], axis=1, inplace=True)

In [12]:
df['gdpp'] = df['gdpp'].apply(lambda x: np.log(x) if x > 0 else 0)
df['income'] = df['income'].apply(lambda x: np.log(x) if x > 0 else 0)

In [ ]:
"""use power transformation to avoid crash as an inflation columns has 0 and negative variable ."""
from sklearn.preprocessing import PowerTransformer

# columns you want to transform
cols = ["inflation"]

pt = PowerTransformer(method="yeo-johnson", standardize=False)

df[cols] = pt.fit_transform(df[cols])

In [14]:
df

     child_mort  exports  health  ...  life_expec  total_fer      gdpp
0          90.2     10.0    7.58  ...        56.2       5.82  6.315358
1          16.6     28.0    6.55  ...        76.3       1.65  8.316300
2          27.3     38.4    4.17  ...        76.5       2.89  8.402904
3         119.0     62.3    2.85  ...        60.1       6.16  8.169053
4          10.3     45.5    6.03  ...        76.8       2.13  9.409191
..          ...      ...     ...  ...         ...        ...       ...
162        29.2     46.6    5.25  ...        63.0       3.50  7.996317
163        17.1     28.5    4.91  ...        75.4       2.47  9.510445
164        23.3     72.0    6.84  ...        73.1       1.95  7.177782
165        56.3     30.0    5.18  ...        67.5       4.67  7.177782
166        83.1     37.0    5.89  ...        52.0       5.40  7.286192

[167 rows x 9 columns]

In [17]:
from sklearn.preprocessing import RobustScaler
r = RobustScaler()
X = df 
X_scaled = r.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)
X_scaled

     child_mort   exports    health  ...  life_expec  total_fer      gdpp
0      1.316620 -0.907441  0.342391  ...   -1.469565   1.635492 -0.904371
1     -0.050139 -0.254083  0.062500  ...    0.278261  -0.364508 -0.055359
2      0.148561  0.123412 -0.584239  ...    0.295652   0.230216 -0.018613
3      1.851439  0.990926 -0.942935  ...   -1.130435   1.798561 -0.117837
4     -0.167131  0.381125 -0.078804  ...    0.321739  -0.134293  0.408361
..          ...       ...       ...  ...         ...        ...       ...
162    0.183844  0.421053 -0.290761  ...   -0.878261   0.522782 -0.191130
163   -0.040854 -0.235935 -0.383152  ...    0.200000   0.028777  0.451323
164    0.074280  1.343013  0.141304  ...    0.000000  -0.220624 -0.538439
165    0.687094 -0.181488 -0.309783  ...   -0.486957   1.083933 -0.538439
166    1.184773  0.072595 -0.116848  ...   -1.834783   1.434053 -0.492441

[167 rows x 9 columns]

In [18]:
preprocessed_data = X_scaled
preprocessed_data.to_csv('preprocessed_data.csv', index=False)